### ISSUE TITLE
Change S3.upload to make requests from Elixir instead of relying on a shell script

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#11]
When I first implemented uploading jpg snapshot files to S3 I did it using [erlcloud](https://github.com/gleber/erlcloud) in a fairly simple manner and it seemed to work fine locally. 

What I find out later is that at some point (at ~50 requests per second IIRC) this starts rapidly generating `retry later` errors . I looked into it briefly (and also tried [mini_s3](https://github.com/chef/mini_s3) with the same results) but ended up replacing that with a shell script that upload to S3 using Curl, as a temporary solution.

I'm assuming this issue can be at least partly mitigated by configuring Erlang and the http libraries (`lhttpc`, `hackney`) but I haven't had time to delve deeper into it.

The relevant code is in the [EvercamMedia.S3](https://github.com/evercam/evercam-media/blob/b1a3e226b6f84f076634b6f26cd00fdb628704a5/lib/media/s3.ex#L15-L37) module. This is the shell script I used: [s3_put.sh
](https://gist.github.com/mosic/f399c9d64814363d55c9)

**Comment by shankardevy** [comment]
@mosic I looked at the shell script and the relevant code. Do you think replacing this https://github.com/evercam/evercam-media/blob/b1a3e226b6f84f076634b6f26cd00fdb628704a5/lib/media/s3.ex#L15-L37

with call to HTTPotion solve the issue?

**Comment by mosic** [comment]
That would certainly be a better solution than the current one and could serve as a stepping stone, but ideally we would use a popular Erlang/Elixir solution like [erlcloud](https://github.com/gleber/erlcloud).

In other words: yes, right now I'd merge a pull request using a HTTPotion-based solution if it works without issues mentioned above.

**Comment by shankardevy** [comment]
I think we can close this now.
