### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by fteem** [evercam/evercam-media#117]
I am guessing it's the database setup (that seems to be non-existent) on SemaphoreCI.

```elixir
** (exit) exited in: GenServer.call(EvercamMedia.Repo.Pool, {:query, :begin, &EvercamMedia.Repo.log/1, [timeout: 5000]}, 5000)
         ** (EXIT) exited in: GenServer.call(#PID<0.4008.0>, {:query, "BEGIN", []}, 5000)
             ** (EXIT) %Postgrex.Error{message: nil, postgres: %{code: :invalid_password, file: "auth.c", line: "285", message: "password authentication failed for user \"postgres\"", pg_code: "28P01", routine: "auth_failed", severity: "FATAL"}}
```

Thoughts?

**Comment by mosic** [comment]
That would be because we haven't set up anything yet :)

Marco just registered and added the repo to Semaphore as far as I'm aware. I mentioned on Slack than that this needs to be set up, but nice idea to create an issue for it. 

In my mind this isn't a big priority at the moment as some of the tests are failing as of recently and I think @jgarciasacristan is working on them.

**Comment by fteem** [comment]
I thought so. 

Okay, I think that [this](https://semaphoreci.com/docs/databases/postgresql.html) is what we need to read when setting up the database. 
Also, if we are not prioritizing this, I think I am going to unsubscribe from the Semaphore emails, as they are annoying and without any significance at the moment. 

/cc @marcoherbst

**Comment by mosic** [comment]
Good call. This is how we're setting up tests for API and Dashboard:
https://github.com/evercam/evercam-api/blob/master/.travis.yml
https://github.com/evercam/evercam-dashboard/blob/master/.travis.yml

**Comment by marcoherbst** [comment]
All good with me. I was really just messing around to understand what it
was. You chaps go with whatever you like.
I will remove us from Semaphore anyhow.
M

On 30 October 2015 at 15:20, Miloš Mošić <notifications@github.com> wrote:

> Good call. This is how we're setting up tests for API and Dashboard:
> https://github.com/evercam/evercam-api/blob/master/.travis.yml
> https://github.com/evercam/evercam-dashboard/blob/master/.travis.yml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/117#issuecomment-152554083>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
@mosic

**Comment by mosic** [comment]
Done, closing.
