### ISSUE TITLE
For discussion with AWS

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#119]
- [ ] Master Slave architecture ... big machines v small machines
- [ ] AWS DB v Postgres
- [ ] Moving from Heroku
- [ ] Cost of jpeg storage / alternatives

@shankardevy  @azharmalik3 @mosic @fteem  ... put any random ideas in here we can clean them up later.

**Comment by eugenehp** [comment]
@marcoherbst  A farm of middle sized CPUs with no storage that save jpegs to KV storage like Redis.
