### ISSUE TITLE
Support streaming snapshots via websockets to the live view

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#130]
When we first introduced Elixir into Evercam, I had an idea of replacing the live view which sent requests to the API every second with one that behaves more like streaming video. That has been half-implemented for a while - the live view requests snapshots and they're streamed back via websockets. Now that we have stable recording processes in place we can use them to complete this.

There are two changes needed in order for this to work:
* we need to add a camera specific token on the dashboard side which is used for authentication when a browser joins the camera websockets channel.
* when the browser is authenticated we need to start a recording process and start streaming snapshots to it. If there is a recording process already started, it would just work. The recording process should stop when the websocket is disconnected unless the camera is set to record every second.

**Comment by mosic** [comment]
Tasks:
- [ ] Use websockets for streaming on the Dashboard live view tab
- [ ] Use websockets for streaming on the Dashboard live view widget
- [ ] Use longpolling for old browsers (< IE9) https://github.com/evercam/evercam-media/issues/140

**Comment by marcoherbst** [comment]
I'll close this, seems it's done.
