### ISSUE TITLE
Switch to using the new database for camera_activites

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#134]
We're currently using the new "snapshot" database only for `snapshots`. We should also use it for `camera_activities`.

**Comment by eugenehp** [comment]
:+1:

**Comment by marcoherbst** [comment]
This is the leftover item from: https://github.com/evercam/evercam-api/issues/475#issuecomment-158354191

It strikes me that this is a pretty high priority item. @mosic , top of your list, eh?

Thanks @azharmalik3 for the reminder.

**Comment by mosic** [comment]
Done in https://github.com/evercam/evercam-media/pull/150/.
