### ISSUE TITLE
Camera went offline 10 days ago, but still shows online

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#136]
https://dash.evercam.io/v1/cameras/hikvis-nz9

Same issue here:

https://dash.evercam.io/v1/cameras/13-north-george/live

On a more positive note, I am pleased to see that it is retrieving the last available snapshot. THAT is a good thing for the dashboard to have done. It would be nice though if it made it clear that the cam was offline and that this was the last available .

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-media/commit/eff77422b0a0ed5efc6f85e15f15914926df434f and https://github.com/evercam/evercam-media/commit/adaf0a6f17069eddb2e4d015a9c8826bed328416.
