### ISSUE TITLE
Websockets fallback

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#140]
This was originally proposed by @azharmalik3 , in theory it's not so useful as if websockets is dead, well that probably means that the media server is dead.

But, then, funnily enough, we discovered that we have a client who is important and is very keen on IE9:
http://caniuse.com/#feat=websockets

So, we might find we do need to tackle this after all. As I'm typing this I realise it probably belongs in dashboard not in media. I'll tag Azhar and see what happens.

M

**Comment by mosic** [comment]
Actually Phoenix has fallback from websockets to long-polling, which we can use in this case: http://www.phoenixframework.org/docs/channels

I'm assuming we will re-enable websockets next week. I'll then check if there's something we need to configure for this or if it's automatic.

**Comment by marcoherbst** [comment]
Sounds good. Also today the customer said they would upgrade to IE10. So that issue is off the table.

I created an issue today whereby Widget it failing on iPhones. This is somewhat related.

M
