### ISSUE TITLE
Move database from heroku to aws

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#142]
Sometime ago when we moved `snapshots` table to a secondary database, @marcoherbst said he is in favor of moving the db from heroku to aws. It was decided at that time that this will be done after sometime and priority being to move the `snapshots` table to secondary database (currently on heroku). 

Creating this issue so that we don't forget this task. This also needs to be done before we work on optimizing `media` for better utilization of AWS resources from the cost perspective.

//cc @mosic

**Comment by marcoherbst** [comment]
Given the upcoming move towards Hetzner, I think this issue is kind of irrelevant. Closing.
