### ISSUE TITLE
GET snapshot request to Evercam Capture doesn't work with HTTPoison/hackney

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#147]
I was looking into why the Evercam Capture doesn't work with the live view and I narrowed it down to this line: [http_client.ex#L17](https://github.com/evercam/evercam-media/blob/955cfd96b6c70d9c55edb43105b964ded94f4e53/lib/evercam_media/http_client.ex#L17)

This is an example of the error caused by this:

``` elixir
iex(1)> HTTPoison.get "http://ssh.evercam.io:10569/back.jpg", [], hackney: [basic_auth: {"hRtGa2", "RmYUkv"}]

** (CaseClauseError) no case clause matching: {:error, :bad_request}
      (hackney) src/http/hackney_response.erl:74: :hackney_response.wait_status/1
      (hackney) src/hackney.erl:360: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:394: HTTPoison.Base.request/9
```

Because this seems to only happen with that app I've made a special case for it and used HTTPotion, which works nicely so far: [http_client.ex#L20-L23](https://github.com/evercam/evercam-media/blob/955cfd96b6c70d9c55edb43105b964ded94f4e53/lib/evercam_media/http_client.ex#L20-L23), but we should try and solve this using HTTPoison/hackney.

**Comment by marcoherbst** [comment]
@scandox .... you've made the point recently that doing a http request is, in it's essence, a pretty basic thing for a web application to be doing. Here is a nice example of us doing just that ... a pretty basic request, nothing fancy, and it not working. I wonder if this isn't a thread worth pulling.

**Comment by marcoherbst** [comment]
Also, well done @mosic  for fixing this. That's great.

**Comment by marcoherbst** [comment]
Simple solution: We killed Evercam Capture.
