### ISSUE TITLE
HLS stream: If the stream doesn't contain audio, it shouldn't declare a track.

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-media#148]
This is related to playing HLS stream in ExoPlayer on Android

https://github.com/google/ExoPlayer/issues/970

**Comment by marcoherbst** [comment]
@mosic @liutingdu @GNUDimarik  ... I've just posted a bounty on the NGINX bug, FYI.:

https://www.bountysource.com/issues/28646289-how-to-disable-audio-track-for-hls

:)

M

**Comment by GNUDimarik** [comment]
You are the Man :)
22 янв. 2016 г. 12:07 пользователь "Marco Herbst" <notifications@github.com>
написал:

**Comment by mosic** [comment]
Nice :+1:

**Comment by mosic** [comment]
@marcoherbst I've solved partially by adding a silent track in ffmpeg, but it would be nice if nginx-rtmp worked as intended. Should we close this issue or?

**Comment by marcoherbst** [comment]
Yes. We've enough other issues to worry about :)
