### ISSUE TITLE
Fake S3 for developer environment.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#15]
One issue with this that I'm aware of but not sure how to fix yet is using S3, evercam-media assumes that it has access to a valid S3 bucket for uploading snapshots. This means that the application will log an error when it tries to upload a file. The way we fixed this for evercam-api in development was using FakeS3: https://github.com/jubos/fake-s3

Suggestions and ideas regarding this or evercam-media and evercam-devops in general are welcome

**Comment by eugenehp** [comment]
@marcoherbst any idea on this since then?

**Comment by marcoherbst** [comment]
Judging by the high standard of english, I'd say I copied and pasted that text from @mosic .

The whole task of running a realistic version of evercam-media locally is a thorny one. @shankardevy  has spent much of the last few weeks working on that. I believe that there was a leap of progress this morning which should be of interest to you and I guess that Shankar will let us know about it later today. It was more to do with the DB than S3, but I think he'll have something to say. 

Is this a blocker for you right now?

M

**Comment by eugenehp** [comment]
@marcoherbst kind of.

```
[warn] Retrying S3 upload for camera 'evercam-remembrance-camera', try #1
[info] Response isn't an image for camera 'evercam-remembrance-camera'
[debug] SELECT c0."id", c0."owner_id", c0."model_id", c0."exid", c0."name", c0."thumbnail_url", c0."is_online", c0."is_public", c0."config", c0."last_polled_at", c0."last_online_at", c0."updated_at", c0."created_at" FROM "cameras" AS c0 WHERE (c0."exid" = $1) ["evercam-remembrance-camera"] (0.9ms)
[debug] UPDATE "cameras" SET "config" = $1, "created_at" = $2, "exid" = $3, "is_online" = $4, "is_public" = $5, "last_online_at" = $6, "last_polled_at" = $7, "model_id" = $8, "name" = $9, "owner_id" = $10, "thumbnail_url" = $11, "updated_at" = $12 WHERE "id" = $13 RETURNING "id" [%{"auth" => %{"basic" => %{"password" => "guest", "username" => "guest"}}, "external_host" => "149.5.38.22", "external_http_port" => 80, "external_rtsp_port" => 90, "internal_host" => "", "internal_http_port" => 0, "internal_rtsp_port" => 0, "snapshots" => %{"jpg" => "/Streaming/Channels/1/picture"}}, {{2015, 7, 30}, {7, 2, 29, 437936}}, "evercam-remembrance-camera", true, true, {{2015, 7, 30}, {7, 9, 33, 0}}, {{2015, 7, 30}, {8, 9, 17, 0}}, nil, "Evercam Devcam", 2, nil, {{2015, 7, 30}, {7, 2, 29, 437936}}, 3] (2.5ms)
```

I think I'll wrap it into a higher level class, and then simply mock it for the tests.

**Comment by marcoherbst** [comment]
No longer relevant, I guess.
