### ISSUE TITLE
Add Authentication to the onvif endpoints when id= is used.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#153]
We need to check user rights for onvif requests. I'm going to Assign @fteem on this, even though it's far out of your scope right now, I just would like you to be aware of it.

**Comment by jgarciasacristan** [comment]
I wonder if this would fix the problem. I have created a new route that will use both the Authentication and ONVIF plugs.  Then it is just a matter of not allowing the id parameter in the query string. See https://github.com/jgarciasacristan/evercam-media/commit/82f6c92957732f1d6bb5612d43e2130a4e40c187

**Comment by ijunaid8088** [comment]
As an update: I have fixed the issue and now the routes are being authenticated but fixing the tests now..

**Comment by ijunaid8088** [comment]
done
