### ISSUE TITLE
Use a date/time folder structure on S3 ... 

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-media#154]
In camba.tv we are using folder structure like `camera-id/year/month/day`.

Using this structure make us easy to delete camera histories.

**Comment by mosic** [comment]
For clarification: this is about the directory/file structure used for storing snapshots in S3.

**Comment by marcoherbst** [comment]
Also, @azharmalik3 mentioned that daterange queries were not working well on S3 and thought that maybe using YYYYMMDDHHMMtttt type format would help here. .... If true, this might also mean we don't need the folder structure.

**Comment by marcoherbst** [comment]
@mosic , I think we can close this now, right?

**Comment by mosic** [comment]
Yep.
