### ISSUE TITLE
Log info makes iex unusable

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#16]
Running
```
iex -S mix
```
starts workers for three cameras in my dev environment. The constant log messages that comes up makes it impossible to use the iex session.

**Comment by mosic** [comment]
Thanks for creating this issue. I planned on adding a command line argument to disable starting workers, as they're not always needed in development. If that's your main concern, you can either implement the argument switch or just comment out this line which starts the workers: [worker_supervisor.ex#L9](https://github.com/evercam/evercam-media/blob/306b4d7efdb4ce44f97ba9878de550765ef88911/lib/media/worker_supervisor.ex#L9)

But if you're only bothered by constant log output you can use a remote iex shell for commands:

Start the Phoenix server:
```
iex --sname evercam -S mix phoenix.server
```
Now note what the full name of the node is on the first line that begins with `iex`- it's in the format of `{{node name}}@{{host name}}`. If using the`evercam-devops` VM the node name is `evercam@vagrant-ubuntu-trusty-64`.

In other terminal tab/window start the remote shell:
```
iex --sname remote_evercam --remsh evercam@vagrant-ubuntu-trusty-64
```

That way you can run all commands in the remote shell without being swarmed by log messages.

**Comment by shankardevy** [comment]
@mosic how about something like this?

```elixir
def initiate_workers do
    case System.get_env["SKIP_CAMERA_WORKER"] do
      "true" -> IO.puts "Skipped camera workers"
      _ -> EvercamMedia.Repo.all(Camera)
           # |> Enum.filter(&(Camera.recording? &1))
           |> Enum.map(&(start_camera_worker &1))
    end
  end
```

and then start `iex` with `SKIP_CAMERA_WORKER=true iex -s mix`

working with the production db, the activity noise is too much. Your solution of remote shell works but still the unnecessary upload to s3 while I am least interested to in s3 process is a overhead on prod cameras and s3 billing.

**Comment by mosic** [comment]
@shankardevy Sure, that's a reasonable way to do it. The other way would be starting `iex` with `iex -S mix --skip-camera-workers` and checking `System.argv` for that argument.

The problem of unnecessary upload to S3 still exists though, as a snapshot is uploaded every time we get an image from a camera. We can add flag for that too, but it maybe makes more sense to disable it in development mode and enable it using an command line argument to `mix`.

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-media/pull/37.

@shankardevy You can use the above change by starting `evercam-media` with this command: `skip_camera_workers=true iex -S mix phoenix.server`
