### ISSUE TITLE
Authorize requests to HLS streams

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#171]
Currently we authorize RTMP streams using nginx-rtmp `on_play` mechanism: https://github.com/arut/nginx-rtmp-module/wiki/Directives#on_play

HLS streams are only available if the camera is public. We should add authorization to HLS streams too, so they can be used with private cameras.

**Comment by marcoherbst** [comment]
@mosic, @liutingdu is implementing EXOPlayer to play HLS on Android. She should be ready to deploy next week. She will go live with a version whereby if no HLS then revert to Jpeg (even if RTSP exists). This is just FYI, in case you foresee problems with that.

**Comment by mosic** [comment]
That sounds like a good compromise until this issue is fixed.

**Comment by mosic** [comment]
@liutingdu This issue has been fixed and the HLS stream is available in the camera object for both public and private cameras as of now.

**Comment by liutingdu** [comment]
:+1:
