### ISSUE TITLE
HLS stream isn't started automatically

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#172]
HLS stream currently doesn't work unless RTMP stream is started. This is a bug.

**Comment by liutingdu** [comment]
@mosic any idea when this will be looked at?

**Comment by mosic** [comment]
@liutingdu Most likely next week.

**Comment by mosic** [comment]
@liutingdu As promised, this has been fixed today.

**Comment by liutingdu** [comment]
@mosic Thanks!
