### ISSUE TITLE
Replace Timex with Calendar

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#19]
this is not critical. [Calendar](https://github.com/lau/calendar) seems to have a nice api and plays well with Ecto. Either Timex needs an upgrade (as the current one didn't work for s3 patch and hence I used calendar) or all call to Timex (2 places currently) needs to be replaced with Calendar. I am opting to replace with Calendar. Comments welcome.

**Comment by shankardevy** [comment]
Location 1:

https://github.com/evercam/evercam-media/blob/master/lib/snapshots/snapshot_fetch.ex#L56

to be replaced with 
```
 Calendar.DateTime.now_utc |> Calendar.DateTime.Format.unix
```

Location 2: 

https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L89-L90

@mosic will you be able to give me an example value `time` as passed to `check_token_expiry(time)`? Is it in unix timestamp or something else?

**Comment by shankardevy** [comment]
on closer look, it looks like the second reference to Timex is not used really in snapshot_controller.ex.

The reference to the function call is commented out.
https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L65

@milos can you please brief if this is a WIP and should there be some token validation. I can start working on it, if need be.

**Comment by mosic** [comment]
Timex library isn't used a lot so it's not a problem to change it, but I'm surprised you had issues with it. Can you elaborate?

Regarding `check_token_expiry`, I commented it out while testing and haven't reverted. The expected time format is ISO8601 (e.g. 2015-07-21T13:57:30Z), generated in the [`evercam-api`](https://github.com/evercam/evercam-api/blob/3d03036fd5e354feaee7083d7d70e52176021446/app/api/v1/routes/snapshot_routes.rb#L43).

**Comment by shankardevy** [comment]
@mosic see this [possible bug in Timex](https://gist.github.com/shankardevy/87d0a72f152908014f74). `Timex.Date.local` says my gmt_offset_std: 330 (5.5hrs) but when I format it says my timezone is '+0500' which makes the s3 think that I am making a request 30 mins after I created the token and says the token is expired.

**Comment by shankardevy** [comment]
Since the recent work with Scheduling is already using Timex, it's now slightly more work to remove Timex. @mosic could you please make use of `Calendar` for any future need for `Timex` so that we don't continue using two different Time libraries and make it difficult to remove one later?  This issue can be open and when we have time to replace `Timex` with `Calendar` on the Scheduler, we could update the mix file and close this issue.

For the same reason, I think we should also stick with httpoison for any http client calls and avoid using httpotion.

**Comment by mosic** [comment]
We aren't using Timex any more.
