### ISSUE TITLE
Implement /v1/cameras/:id endpoint from evercam-api

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#192]
This involves:
- [x] a new route
- [x] rendering JSON views
- [x] displaying if the requester is the camera owner
- [x] support for mac address field
- [x] support for geolocation field
- [x] generating "rights" list correctly 
- [x] generating RTMP and HLS urls with tokens
- [x] rendering timestamps correctly
- [x] rendering internal config
- [x] rendering external config
- [x] authentication
- [x] authorization
- [x] all other camera attributes
- [x] support for user requests
- [x] support for client requests

**Comment by marcoherbst** [comment]
@mosic  ?

**Comment by mosic** [comment]
@marcoherbst Thanks for the ping, I meant to close this when I renamed the issue.
