### ISSUE TITLE
2 new endpoints needed for ptz/presets

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-media#197]
1 Delete  ptz/presets/{preset_name} or {token}
 2 Patch  ptz/presets/{preset_name} or {token}

Currently, we don't have these 2 endpoints,so once a preset is made it can neither be edited nor destroyed.

**Comment by marcoherbst** [comment]
Thanks Muneeb. @jgarciasacristan is this really the case ? none of the onvif endpoints allow modification of ptz points? Or, where should Muneeb look?

m

**Comment by jgarciasacristan** [comment]
To delete a token the following endpoint can be used

/v1/onvif/v20/PTZ/RemovePreset?id={camera_id}&ProfileToken=Profile_1&PresetToken={preset_token}

OnVIF does not provide Preset Modification. If you want to modify a preset,
you need to delete/create. See all onvif ptz commands in
www.onvif.org/onvif/ver20/ptz/wsdl/ptz.wsdl

Let me know if the endpoint makes sense above makes sense and can be easily
integrated.

**Comment by marcoherbst** [comment]
That's perfect. Tks.

**Comment by marcoherbst** [comment]
@muneeb2542  is this issue still open? Or do you agree that the endpoint you need already exists?

**Comment by muneeb2542** [comment]
@marcoherbst  i think we will need that endpoint afterall because i have tried a lot and still we cannot send an ajax request for the camera to the above endpoint.

![screenshot from 2016-04-26 13-09-44](https://cloud.githubusercontent.com/assets/6482077/14811229/8c4cc342-0bb0-11e6-960c-01272a265ea0.png)

**Comment by jgarciasacristan** [comment]
@muneeb2542  try to use a GET instead of a DELETE operation as the endpoint uses the GET method to invoke OnVIF operations. 

https://github.com/evercam/evercam-media/blob/master/web/router.ex#L72

**Comment by muneeb2542** [comment]
@jgarciasacristan i have used get with it,it is showing a 404 error.

![screenshot from 2016-04-26 14-30-53](https://cloud.githubusercontent.com/assets/6482077/14813527/86d27460-0bbb-11e6-889b-a3c175d88c43.png)

**Comment by muneeb2542** [comment]
@marcoherbst  I don't think we need another endpoint anymore,the endpoint suggested by @jgarciasacristan for ptz deletion is working just fine and I am going to deploy it later today.So this issue is irrelevant now.

Closing this

**Comment by marcoherbst** [comment]
Excellent. :)
