### ISSUE TITLE
Add support for updating camera information for recording camera processes

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#20]
Currently the only time when a camera worker is updated is when the `initiate_workers` function is called, i.e. when starting the server.

We should replace a camera worker process whenever the camera data is changed. This is a bit trickier than it sounds as the change in the data may be caused by `evercam-api`, so we need to either be notified of every change from the `evercam-api` or to listen/subscribe to the changes on the `cameras` table.

**Comment by marcoherbst** [comment]
This is a note to say that the same thing seems to be happening with rtsp streams too. (ffmpeg instances, I guess.)

**Comment by shankardevy** [comment]
during my skype call with @milos regarding this issue, we decided that we create a new url in evercam-media '/v1/cameras/:id/touch' that is called by api whenever new camera is added or existing ones updated.

this url is no going to seen by the end users and will not be required when api is fully migrated to elixir.
