### ISSUE TITLE
Improve port check endpoint

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#203]
Ideas welcome.

**Comment by liutingdu** [comment]
Add authentication?

**Comment by marcoherbst** [comment]
I think that for our RTSP ports, we're relying on TCP to check if they're open.
Given that most cameras use UDP on RTSP ports, I have a hunch that this check is irrelevant.
If I'm right, then we probably should remove the port check from the RTSP port.

In other news, I like telling UDP jokes because I don't care if you don't get them.

**Comment by mosic** [comment]
Not sure what you mean by removing the port check, we haven't added it yet: https://github.com/evercam/evercam-media/issues/231

We use TCP for streaming RTSP ([stream_controller.ex#L82](https://github.com/evercam/evercam-media/blob/788b836ad00597b34c86640824df4a738edfbd0d/web/controllers/stream_controller.ex#L82)) so adding the check still sounds like a good idea to me.

**Comment by marcoherbst** [comment]
We've added it to Dashboard (when adding a camera). 

And, ok, good, I see what you mean. I had it in mind we were using UDP for the RTSP stream, but your code suggests that we're forcing TCP. If I remember right, we chose this road as it is the quickest to load in most situations (The alternative is trying udp first and falling back to tcp). Does any of this sound right?

M

**Comment by mosic** [comment]
Yes, that's how I remember it too.

**Comment by marcoherbst** [comment]
@azharmalik3 thinks ffmpeg might have a fast process for validating udp packets . Could this be a quick way to see if an rtsp URL is valid ?

**Comment by marcoherbst** [comment]
I see nothing useful in this ticket anymore. Azhar has one open for the ffmpeg RTSP stream test, that'll do.
