### ISSUE TITLE
Logs should show last cause of going offline

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#210]
@mosic I thought we discussed this and created an issue for it ... but I dont see it. So I'm making this one.

Is it correctly described? What actually do we want here?

This will impact on Clients: Dash, Ios, Android

**Comment by mosic** [comment]
Yes, this is correct. We will add the error code (e.g. "device_busy") to the `extra` field in logs for the "offline" action, so clients can display it.

**Comment by azharmalik3** [comment]
Completed in media and create an [issue](https://github.com/evercam/evercam-dashboard/issues/1409) in dashboard for @muneeb2542 to display offline log reasons.
