### ISSUE TITLE
The online event is logged multiple times

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#213]
![image](https://cloud.githubusercontent.com/assets/1229422/14915894/86362224-0e16-11e6-958a-dbcf1fc5d119.png)

As seen on the screenshot, there is one offline event then three online events in a span of a couple of seconds. This seems like a race condition when changing the camera status.

**Comment by azharmalik3** [comment]
Milos already fixed this issue. [Reference](https://github.com/evercam/evercam-media/commit/1c28484b3c38118aec319c3c4080271aa52b02f6#diff-f335932982d6dfdccf69bbfd990e6ae8)

**Comment by marcoherbst** [comment]
@azharmalik3  ... so close it?
