### ISSUE TITLE
Logs online/offline duplication ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#215]
... sometimes it comes online 3 times.
![screenshot-dash evercam io 2016-05-03 09-10-24](https://cloud.githubusercontent.com/assets/5648894/14977779/0244726c-110f-11e6-87a3-4db433d7b2c2.png)

@mosic I know we discussed this. Is this the right place for this issue? More info if you have it pls.

**Comment by mosic** [comment]
I made an issue for this already: https://github.com/evercam/evercam-media/issues/213

Closing this.
