### ISSUE TITLE
Deleting not working?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#223]
This camera is on 24hr recording but has several months' history. @mosic

**Comment by mosic** [comment]
That sounds like a bug. What camera are you referring to? I'm guessing you were meaning to attach a screenshot for this issue.

**Comment by marcoherbst** [comment]
Yes, I did, but it seems to be true for every camera I've looked at:
https://admin.evercam.io/cloud_recordings

m

**Comment by ijunaidfarooq** [comment]
it seems to be working so am closing this issue!
