### ISSUE TITLE
Better handling of bad RTSP urls

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#231]
Quite a few cameras have bad rtsp URLS either due to closed ports or incorrect URLs.

Currently Evercam tries hard to open these URLS and it's a dull process waiting for it to fail.

Can we fail faster?

**Comment by mosic** [comment]
Good question. Yes, we can check if the port is open when doing the authorization check.

Junaid (or I) can do this after this pull request gets merged: https://github.com/evercam/evercam-media/pull/228

**Comment by azharmalik3** [comment]
Added port checks as Milos mentioned.

Now closing this because of added issue to determine bad RTSP URl's. #466
