### ISSUE TITLE
Possible Caching issue effecting logs ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#256]
![image 1](https://cloud.githubusercontent.com/assets/5648894/16089637/fc312fa0-3323-11e6-9d90-33ec73a4149e.png)

Sometimes I see more online events than offline. 

Wierd.

**Comment by azharmalik3** [comment]
@marcoherbst It's not a cache issue. It was an issue in the system to log online events multiple times #213 .

**Comment by marcoherbst** [comment]
So case closed?

**Comment by azharmalik3** [comment]
Yes.
