### ISSUE TITLE
Drop snapshots table

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#263]
This issue is for tracking the requirements needed to get rid of the snapshots table:

- [ ] Migrate Snapshot Endpoints from evercam-media
  - [x] POST /cameras/:id/recordings/snapshots
  - [ ] ~~GET /cameras/:id/recordings/snapshots~~
  - [x] GET /cameras/:id/recordings/snapshots/:timestamp
  - [x] GET /cameras/:id/recordings/snapshots/:year/:month/:day
  - [x] GET /cameras/:id/recordings/snapshots/:year/:month/:day/:hour
  - [x] GET /cameras/:id/recordings/snapshots/:year/:month/:day/hours
  - [x] GET /cameras/:id/recordings/snapshots/:year/:month/days

- [ ] Import existing snapshots into seaweedfs
  - [x] Import snapshots stored on S3
  - [ ] Import snapshots stored on Hetzner

- [ ] Use seaweedfs for snapshot cleanup, not snapshot table data

**Comment by marcoherbst** [comment]
I have a hunch that some endpoints, such as:

 DELETE /cameras/{id}/recordings/snapshots/{timestamp}

have never been used and were built only because we thought we need them.

If you can spot any endpoint that you think is not in use, then you are doing a wonderful thing if you flag it to not be re-created.

**Comment by mosic** [comment]
@marcoherbst Good point, I'll remove that and add support for automated snapshot cleanup from seaweedfs.

**Comment by marcoherbst** [comment]
This issue might be better replaced by two others:
1. Camera Activities New Arrangement
2. Steps to take once SeaweedFS import is completed

Right? @mosic  ?

**Comment by marcoherbst** [comment]
I'll close this, seems done.
