### ISSUE TITLE
Invalidate camera caches when a user deletes their account

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#285]
We should invalidate cache for all users who had a camera in their account which was owned by the deleted user.

Also, the same thing is true if a user shares a camera with someone, then deletes it.

**Comment by ijunaidfarooq** [comment]
@azharmalik3 its done? eh?

**Comment by azharmalik3** [comment]
Yes.

**Comment by mosic** [comment]
This is not done. See my TODO comment here: https://github.com/evercam/evercam-media/blob/bc8e359af216c5e2c0c597690524fdc5ba5f6477/web/controllers/user_controller.ex#L167

**Comment by azharmalik3** [comment]
Done.
