### ISSUE TITLE
Switch to using HTTPoison 100%

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#287]
The only two places where we're using `HTTPotion` instead are Onvif and Intercom clients.

**Comment by ijunaidfarooq** [comment]
Any reason of preference to HTTPoison?

**Comment by marcoherbst** [comment]
It was just that we experimented in the past with both ... and have now settled on Poison. So, no reason.

Junaid, you might find that Jose is busy, I would suggest you could also make the PR for him.

**Comment by mosic** [comment]
Not exactly no reason.

We have had performance issues with `HTTPotion` before caused by unusual defaults (number of ETS tables limiting the number of requests to different hosts). `HTTPoison` has a nice API, it's easy to use and configure (set auth, pooling, headers etc.), and the performance issue that we encountered with it was quickly fixed.

There is no good reason to use `HTTPotion` instead (that I know of), and having consistency across the database makes it worth to stick to one library.

**Comment by ijunaidfarooq** [comment]
I was only confused due to some reasons as HTTPoison says its based on HTTPotion. 

> HTTP client for Elixir, based on HTTPotion (documentation).

But I came to know that its not the same.. as **HTTPoison is built on hackney, HTTPotion is built on ibrowse**

**Comment by ijunaidfarooq** [comment]
HTTPoison has been added to intercom client and merged as well

But on onvif side by adding HTTPoison lots of tests start failing, So I left that one for a while

**Comment by ijunaidfarooq** [comment]
Hi @jgarciasacristan as you follow up the issue. 

I have changed the needed things to switch to HTTPoison in OnvifClient.

there was only one difference in data coming from HTTPoison and HTTPotion 
{:ok, response} and only response. I added that in https://github.com/evercam/evercam-media/blob/switch_to_HTTPoison_in_onvif_client/lib/evercam_media/onvif/onvif_client.ex#L39

Now the passed response to the below data is the same as it was coming from HTTPotion.
Results: Everything is working fine! I have tested Presets locally! and it's working well. But Tests are failing, Totally.. with the same error which is written below

```
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}
```

any input from your side to this? relevant branch is this https://github.com/evercam/evercam-media/tree/switch_to_HTTPoison_in_onvif_client

**Comment by jgarciasacristan** [comment]
Hi Junaid,
Don't have time to look much at it as I am currently back on holidays in
Spain,
OnVIF tests are using ExVCR.Mock, so that may be an issue. One way to see
if it is a problem with the mock is to run
https://github.com/evercam/evercam-media/blob/switch_to_HTTPoison_in_onvif_client/test/controllers/onvifptz_controller_external_test.exs
and
https://github.com/evercam/evercam-media/blob/switch_to_HTTPoison_in_onvif_client/test/onvif/external_ptz_test.exs.
These tests are talking to the camera directly, so they should pass.
Let me know how it goes.

**Comment by ijunaidfarooq** [comment]
thanks, @jgarciasacristan . I will update you on this!

**Comment by ijunaidfarooq** [comment]
@jgarciasacristan Yes, the both files passed very well.

```
2 tests, 0 failures, 6 tests, 0 failures
```

**Comment by jgarciasacristan** [comment]
Great news!
You will need to re-generate the files stored in
https://github.com/evercam/evercam-media/tree/switch_to_HTTPoison_in_onvif_client/test/fixtures/vcr_cassettes
.
Look at https://github.com/parroty/exvcr for info. Looking at the changes
made to the test files will help you to figure out how to recreate the
files (you will need to revert the URL used in the tests to a real one)
Good luck!
Jose

**Comment by marcoherbst** [comment]
Happy holidys @jgarciasacristan  :)

**Comment by jgarciasacristan** [comment]
Thanks! :-)

**Comment by ijunaidfarooq** [comment]
its done! HTTPotion was also present in Public controller. So its been switched to HTTPoison as well..
