### ISSUE TITLE
Archive Replay Speed Choices .... re assess

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#294]
Looks like we replay @ 24fps with x0.25 to x8 replay speed options.

We should probably default to replaying @ the recorded speed and offer better options for faster / slower if possible.

@vinnieq you reported this.

.

**Comment by azharmalik3** [comment]
@marcoherbst When I used recorded speed it makes a large file with very slow speed.
Our maximum recording  speed is 1 frame per second which is also enough to make slow speed video. 1 frame every 2 seconds and other settings make a too slow video and a large one.

**Comment by marcoherbst** [comment]
@azharmalik3  I bet that's only true if your IFRAME settings are low. Please paste here the full ffmpeg string.

I'm going to suggest something like:

Replay @ 1fps, with IFRAME Interval of 4 seconds. 

"Fast" & "Slow" *& "Big" are not very useful words to use in this conversation. We know that the max clip length is 2hrs (Evercam Limit, right?). So, we're dealing with no more than 7000 frames.

Typically a clip is less than 5 minutes. 

If it makes life much easier, we could set a limit that clips are no more than 30 minutes and we could change the interface to specify a start time & duration (rather than start & end-time). That might be for another ticket, but first I'd like to hear your thoughts. Voice call if you wish.

**Comment by marcoherbst** [comment]
Also, I'm migrating this comment from an issue on the dashboard:

Why is the clip quality so poor? 
https://dash.evercam.io/v1/cameras/evercam-remembrance-camera/archives#

It's related.
If you are using image compression on clip generation - dont. (other than iframe interval).

**Comment by azharmalik3** [comment]
@marcoherbst I am using this FFmpeg command:

`ffmpeg -r 24 -i image%d.jpg -c:v libx264 -r 24 -profile:v main -preset slow -b:v 1000k -maxrate 1000k -bufsize 1000k -vf scale=-1:720 -pix_fmt yuv420p -y output.mp4`

**Comment by marcoherbst** [comment]
-r (Frame Rate 24 input)
- i  (file names)
-c (codec) video h264
-r (Frame Rate 24 output)
- profile (quality)
preset https://trac.ffmpeg.org/wiki/Encode/H.264 ( from reading this, I'd like to try removing profile & using preset -tune stillimage )

**Comment by azharmalik3** [comment]
Completed and created an [issue](https://github.com/evercam/evercam-dashboard/issues/1441) in the dashboard for interface changes.
