### ISSUE TITLE
Add PTZ functionality using OnVIF commands to the camera

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#3]
We're thinking of starting with: 

/cameras/{camera-id}/ptz/presets
/cameras/{camera-id}/ptz/presets/home
/cameras/{camera-id}/ptz/relative?left=10,up=10
/cameras/{camera-id}/ptz/continuous/start/left
/cameras/{camera-id}/ptz/continuous/stop

and using https://github.com/r-icarus/detergentex for handling the SOAP requests to the camera.

**Comment by jgarciasacristan** [comment]
I had a quick look at detergentex and is really basic, a small wrap to https://github.com/devinus/detergent.  From what I have seen from the erlang code, it does not easily support authorization/authentication, but I hope it can be added into the code.  
I also found one interesting discussion that hints what may be ahead. :-)
http://comments.gmane.org/gmane.comp.lang.erlang.general/73580

**Comment by marcoherbst** [comment]
Good find.

**Comment by jgarciasacristan** [comment]
I have managed to invoke simple onvif commands to Mobile Mast camera using https://github.com/quatanium/python-onvif.  (For all onvif commands see http://www.onvif.org/onvif/ver20/util/operationIndex.html).
Now, I need to be able to invoke the same simple commands using Erlang/Elixir. As of today, detergentex does not support basic authentication in the headers. https://github.com/r-icarus/detergentex/issues/3. Working on enabling that functionality on the library.

**Comment by marcoherbst** [comment]
Nice one !

m

On 21 June 2015 at 12:47, jgarciasacristan <notifications@github.com> wrote:

> I have managed to invoke simple onvif commands to Mobile Mast camera using
> https://github.com/quatanium/python-onvif. (For all onvif commands see
> http://www.onvif.org/onvif/ver20/util/operationIndex.html).
> Now, I need to be able to invoke the same simple commands using
> Erlang/Elixir. As of today, detergentex does not support basic
> authentication in the headers. r-icarus/detergentex#3
> <https://github.com/r-icarus/detergentex/issues/3>. Working on enabling
> that functionality on the library.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/3#issuecomment-113889012>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
I have created a [project] (https://github.com/jgarciasacristan/onvifex) in my personal github page that uses HTTPotion instead of Detergentex (in reality, a thin wrapper of the Erlang [Detergent] (https://github.com/devinus/detergent) ) 
My idea to implement something similar to [ruby-onvif-client] (https://github.com/jimxl/ruby-onvif-client) in Elixir using HTTPotion.

**Comment by marcoherbst** [comment]
Great ! ... Look forward to seeing it evolve, seems like a super tool to
have.
M


On 30 June 2015 at 23:21, jgarciasacristan <notifications@github.com> wrote:

> I have created a project <https://github.com/jgarciasacristan/onvifex> in
> my personal github page that uses HTTPotion instead of Detergentex (in
> reality, a thin wrapper of the Erlang Detergent
> <https://github.com/devinus/detergent> )
> My idea to implement something similar to ruby-onvif-client
> <https://github.com/jimxl/ruby-onvif-client> in Elixir using HTTPotion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/3#issuecomment-117361112>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
Moved my little onvifex codebase to a forked evercam-media repository: https://github.com/jgarciasacristan/evercam-media
I have then created a new route:  /onvif/cameras/:camera_id/ptz/presets that returns the PTZ presets of a given camera in json format. I have also added some unit tests, but at the moment one test is failing because the Repo data is not available at test time. I think I know how to fix it. I'll give it a try this evening. 
For my testing I am using the "mobile-mast" camera. The IP address is even hardcoded in some of the onvif unit tests!  For the phoenix controller test, I added it to my dev environment cameras as "mobile-mast-test".  
@mosic . Could you please review my code when you have some free time?  Be aware that error handling is non existent.  If the code is good enough to be part of evercam-media,  I will start adding more functionality to the controller.

**Comment by mosic** [comment]
@jgarciasacristan Sure, I'll take a look either tonight or tomorrow.

**Comment by jgarciasacristan** [comment]
Thanks Milos,
Just in case you have already looked at my code, I have just made a commit
that reduces the JSON Encoding/Decoding that I had originally. I now work
only with maps until a response is sent back to the browser.
Cheers
Jose

**Comment by jgarciasacristan** [comment]
Routes
    get "/v1/cameras/:id/ptz/status"
    get "/v1/cameras/:id/ptz/presets"
    post "/v1/cameras/:id/ptz/home"
    post "/v1/cameras/:id/ptz/home/set"
    post "/v1/cameras/:id/ptz/presets/:preset_token"
    post "/v1/cameras/:id/ptz/presets/create/:preset_name"
    post "/v1/cameras/:id/ptz/presets/go/:preset_token"
    post "/v1/cameras/:id/ptz/continuous/start/:direction"
    post "/v1/cameras/:id/ptz/continuous/zoom/:mode"
    post "/v1/cameras/:id/ptz/continuous/stop"
    post "/v1/cameras/:id/ptz/relative"
available in my forked repo. I will create a pull request tomorrow evening.

**Comment by marcoherbst** [comment]
That's exciting!!

M

**Comment by mosic** [comment]
@jgarciasacristan Those routes will be a separate pull request? Can this one be merged before it?

**Comment by jgarciasacristan** [comment]
@mosic  Actually, I have added all these extra routes over the weekend to my forked repository. Can I generate a pull request with all my changes so far? If ok, I'll try to generate one later tonight.

**Comment by mosic** [comment]
Sure, that would be great.

**Comment by jgarciasacristan** [comment]
Done. My first pull request. :-) . Now, let's have some dinner.

**Comment by mosic** [comment]
:) Thanks, I'll take a look at it tonight.

**Comment by marcoherbst** [comment]
I think we can close this, eh @jgarciasacristan ?

**Comment by jgarciasacristan** [comment]
Yes.
