### ISSUE TITLE
Newly created camera does not show in the camera's list

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#303]

**Comment by marcoherbst** [comment]
@Zulqarnain-Mustafa  you are going to have to give more details for this to be useful and acted on.

We need to know on what app and what camera and what user and when

Also, I guess, when you logout / login, then it works? 

Or, refresh? 

Or wait 2 mins....

Good effort, but make your bug report more complete please.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  
Application: iOS Application
User: nain@evercam.io
**Camera Details:**
IP: 176.126.42.134
HTTP Port: 8083
Vendor: Sony
Model: SNCCH260

After adding i go to grid view and did not see the newly created camera, then i press refresh button, it did not appear, then i go to dash.evercam.io, it was also not there, So discuss this with @azharmalik3 . 
After wait of about you may 10 mins it appears.

**Comment by mosic** [comment]
@Zulqarnain-Mustafa Thanks for the report, fixed in https://github.com/evercam/evercam-media/commit/4d30b979f1d709a681b5862b012fe6c606112476.
