### ISSUE TITLE
PTZ controls and Preset error for some cameras

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#311]
Here are details of the camera for which i am getting `Error code 500`

```
camId = "everca-pa7";
"camera_Direction" = "up=4";
```

}

**Comment by azharmalik3** [comment]
@Zulqarnain-Mustafa it's not an issue, endpoint gave this message because of you don't have full rights of camera.

**Comment by marcoherbst** [comment]
well, then the bug is "dont show ptz if you only have read-only rights" , yeah?

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst the camera for which we are facing this problem is added from this website [](http://www.insecam.org) and we do not have username and password for this camera, so that is why we are not able to control this camera ptz controls.

**Comment by marcoherbst** [comment]
Ah, we're using a public snapshot URL, so even though you have full-rights to the Evercam share, Evercam does not have suitable rights for the Camera. Interesting. 

I think we should leave this to @ijunaidfarooq to see if maybe he can pass a more useful error message.

**Comment by marcoherbst** [comment]
@azharmalik3 any reason you took this? IMHO :+1: 
1. There is no obvious solution
2. It belongs better in a cluster of Onvif / Ptz tasks currently being handled by Junaid. I think I'll put all PTZ / onvif in another milestone .... ?

**Comment by azharmalik3** [comment]
No reason, I just start milestone from the first issue.

Yes, of course. Move all PTZ / onvif issues in another milestone.

**Comment by ijunaid8088** [comment]
@Zulqarnain-Mustafa This have been done now you can show the message response.. with 404 status code.
