### ISSUE TITLE
Thumbnail is not included in camera share email notifications.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-media#315]
@mosic was there any reason to disable thumbnails?
[cf8804f](https://github.com/evercam/evercam-media/commit/cf8804f6d451d7e51be5d9e242ec0795ec5d6c52)

May I re-enable it?

**Comment by mosic** [comment]
Because the version of mailgun we were using at that time was erroring in production. I added them back in https://github.com/evercam/evercam-media/commit/5a0c9c941d2a1a4042e2e79e4dbd70cbf663c9fd.
