### ISSUE TITLE
Unable to sign in with email address

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#318]
I am only able to sign in with "username", If I enter email address it return error that user does not exist.

**Comment by ijunaidfarooq** [comment]
fixed in https://github.com/evercam/evercam-media/pull/319

**Comment by ijunaidfarooq** [comment]
Please add some information that what issue you are facing? Nain?

**Comment by ijunaidfarooq** [comment]
This Happened due to a old PR merge.. function  `by_username_or_email` was replaced by `by_username` . I have created https://github.com/evercam/evercam-media/pull/355 PR it will be fixed as it will be merged!
