### ISSUE TITLE
I am able to get list of Presets by passing wrong api_key and api_id or leaving it empty

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#322]
As i discussed with @azharmalik3  Preset endpoints does not pass through OAuth, so what is the purpose of passing the api_key and api_id in request? 
I think we should not be able to get presets without api_key and api_id.

**Comment by marcoherbst** [comment]
@Zulqarnain-Mustafa  , this issue already exists here:
https://github.com/evercam/evercam-media/issues/153

So, I'll close this one. 

(BTW, you're totally correct and this is an important issue). Also, correctly speaking we're not using "OAuth", "Auth" would be more accurate.
