### ISSUE TITLE
User credentials endpoint doesn't work

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#327]
Tried it for a valid username and password, it returned "Invalid password".

Also it's a bad idea to use GET method for this, POST would at least keep the sensitive information away from the logs.

**Comment by ijunaidfarooq** [comment]
@mosic It's working I have tried with mine/affan/nain.

**Comment by ijunaidfarooq** [comment]
@mosic @marcoherbst this was related to newly created users. now it's working
