### ISSUE TITLE
No validations on firstname and lastname while user creation.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-media#332]
firstname and lastname has no validation while user creation.Whereas evercam-models has validation.So whenever something is updated, an error is generated for those accounts which have an invalid firstname or lastname or both.

**Comment by ijunaidfarooq** [comment]
@muneeb2542 such kind of Airbrake issues are coming already even before directing towards evercam-media. how its related to validation? 

as this error came 2 months ago https://evercam.airbrake.io/projects/98599/groups/1693842958330262329

**Comment by muneeb2542** [comment]
@ijunaidfarooq it is related to validations,because evercam-models has specifically listed a regex for firstname and lastname.Also such type of error was also happening on evercam-api because there were no validation there also.Plus the error that you are referring to is for username not firstname and lastname.

**Comment by ijunaidfarooq** [comment]
@muneeb2542 Sorry I forgot to mention others.
![selection_045](https://cloud.githubusercontent.com/assets/13561999/17126696/e805e696-5318-11e6-8eb9-5b7156a23221.png)
Am still confused about this validation on firstname or lastname. Are there any users in DB right now? whom first name or last name has not passed validation?

**Comment by muneeb2542** [comment]
@ijunaidfarooq Yes there are you can see in this link

https://evercam.airbrake.io/projects/98599/groups/1737212475416410838

Each of these users have an invalid firstname or lastname or both.

**Comment by ijunaidfarooq** [comment]
@muneeb2542 Right this is a valid issue and **Dashboard Airbrake** filing this for very long time.

**Comment by ijunaidfarooq** [comment]
It's been done on Media.

@muneeb2542 add the same regex to evercam-models to keep it the same for both sides!

**Comment by ijunaidfarooq** [comment]
and follow this regex @muneeb2542 `^[\p{Xwd}\s,.']+$` for first name and last name for more reference see here https://github.com/evercam/evercam-media/blob/master/web/models/user.ex#L7
