### ISSUE TITLE
Evercam-Models

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#337]
What is the future of this repo ?

**Comment by mosic** [comment]
The purpose of `evercam-models` was to be shared between `evercam-api` and `evercam-dashboard`. Now that `evercam-api` is not used any more, `evercam-models` can be merged into `evercam-dashboard`.

**Comment by marcoherbst** [comment]
@muneeb2542  .... do you think you could do this? 
Could you look into the task and work out if you think you can or not ... if not, then now is the time to ask any questions to Milos ....

**Comment by azharmalik3** [comment]
Close this issue because @muneeb2542 importing `evercam-models` into dashboard.
