### ISSUE TITLE
Increase expiry date of access token same as our old API.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-media#338]

**Comment by mosic** [comment]
I just merged a PR that fixes this (https://github.com/evercam/evercam-media/pull/339), but I don't think it's a good solution.

What's the point of an expiry token if we set it to expire in 22 years?

**Comment by azharmalik3** [comment]
@mosic Basically token expiry was used by oAuth. Now We are not  using oAuth, So I think we should remove expiry check because we are totally relying on `api_id` and `api_key`.

**Comment by ijunaidfarooq** [comment]
It's done. But we still thinking about totally neglecting the Expiry token. not decided yet
