### ISSUE TITLE
Set expiry date for jpegs on S3

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#35]
Consider how we want a customer to be able to choose for how long we should store jpegs.

Standard choices: 1 day, 7 days, 30 days, 90 days or custom [   ] days.

If someone is on 7 days and then extends it to 30 days, then the footage recorded @ 7 days will not be deleted after 7 days, but will live longer for the 30 day limit. (And vice-versa).

It is a good idea to have a grace period, if I am on 30 days and reset to 7 days for 5 mins and then move back to 30 days, it would be nice if all of my footage was not deleted. I'd be happy with 24hrs grace.

Images captured via another service (e.g. Motion Detection) do NOT get deleted, ever. This is an important rule as we rely heavily at the moment on being able to retrieve people's Motion Detection requested snapshots. Same would be true for BigRedButton or the 1 jpeg/minute online-offline counter or CCTVSelfies.

I'm cc'ing @shakeelanjum so that you can see the implications here re: Timelapse.

The task belongs to @mosic. There are interace, API and billing implications here too.

M

**Comment by marcoherbst** [comment]
The plan:

Phase 1:

- [ ] Take everyone off infinity who can come off infinity and set the rest to 30 days. (vq)
- [ ] Set frame rate to mininum we can tolerate for all cameras (vq)
- [ ] Remove infinity option from Dashboard.
- [ ] From now on, set appropriate expiry on snapshots and have them auto-delete.

---------------------------------------

This might help: https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/ ? I suppose expiration date also needs to go into the db ?

@mosic  .... I think this is a minimum spec to start reducing the # snapshots we're holding on to. Are you happy with this?

https://docs.google.com/spreadsheets/d/1H9dmVUevg3eKcs1Rgj_vXOdcJTtIgOzIffnbcCx7MZU/edit#gid=0&vpid=A1

M

**Comment by mosic** [comment]
@marcoherbst Yep, that sounds good.

**Comment by marcoherbst** [comment]
I feel like we've done enough of this to warrant it being closed. We took a slightly different approach, and deletion will need revisiting, but this issue can go.
