### ISSUE TITLE
Setup RAID monitoring on Hetzner

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#354]
I think we've got hardware RAID6 on Seaweed & Media.
I think it could be one of 2 adapter types provided by Hetzner.
I think you need to find out which one it is and install the appropriate monitoring tool to let us know about issues.

This is the sort of link that might contain the necessary info:
https://wiki.hetzner.de/index.php/LSI_RAID_Controller/en

**Comment by ijunaidfarooq** [comment]
### **Update:** 
1: put that command to see the manufacturer of the raid controller lspci  | grep RAID
	This will result into `02:00.0 RAID bus controller: LSI Logic / Symbios Logic MegaRAID SAS 2108 [Liberator] (rev 05)`

and install megaCli with [script](https://gist.github.com/ijunaidfarooq/cd0f0695a8232b5641cac32d82a7465b)

After that, you need to create an alias to access the megaCLI which can be done as 

`alias MegaCli="/opt/MegaRAID/MegaCli/MegaCli64"`

Then you can use MegaCli commands as 
`MegaCli -LDInfo -Lall -Aall`

All the commands are same just Hetnzer used an alias as megacli and we are going to use as MegaCli or you can alias it with any name you want to.

**Comment by marcoherbst** [comment]
Worth a look @ijunaidfarooq https://www.nagios.com/solutions/raid-array-monitoring/

**Comment by ijunaidfarooq** [comment]
For follow up for others.

It has been a struggle to add Raid monitoring in Nagios. I have been using `check_raid.pl` which was the common plugin for Raid but as our Raid controller  was `MegaRAID SAS` so  the plugin was different. Which was `check_mega_raid_sas` as a Prerequisite I added MegaCli to seaweed server as well and added the mega raid sas plugin to let communicate it with Nagios Core. Now we can see the Raid status on Nagios core.

The plugin needs some edition before adding. as MegaCLI directory is different while installing so You need to update it in plugin as well. as its getting the full path to the binaries of MegaCLi

**Comment by ijunaidfarooq** [comment]
For follow up for others.

Email notifications(me and Marco) have been setup for any critical process on seaweedFS.  All such information is in `/usr/local/nagios/etc/objects/` on `contacts.cfg`. You need to define **contact** and a **contact group** but with the same user as you created **in the very beginning for login.** 

Any further work on this could be
1: Remove all localhost checks/services.
2: Email templates are not elaborative right now. Just showing small information.

**Comment by marcoherbst** [comment]
Bookmarking this for NVR polling: https://www.monitoring-plugins.org/doc/man/check_http.html
