### ISSUE TITLE
Sharing & New Signup not working (read-only to new account)

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-media#365]

**Comment by ijunaidfarooq** [comment]
Follow Up: Sharer and Owner -> Invalidate cache!

**Comment by ijunaidfarooq** [comment]
After debudding everything! Invalidating the cache of Camera after being shared solved this problem.. in any case whether its read only or full right!

Also Intercom totall actiivity is now being added to background process.

**Comment by marcoherbst** [comment]
That's great news, well done. Thanks. 
I will ask @muneeb2542 to do a test of this new feature. Muneeb, once tested, would you mind adding your comment to this issue. Tks.

**Comment by ijunaidfarooq** [comment]
I would like @faisal2472 to do this as well ! He can see/relate to issue with the perspective of a user, not Developer!  :)

**Comment by marcoherbst** [comment]
I agree 100% on the benefit of a non-dev doing testing, but for now, this one is with Muneeb.

**Comment by muneeb2542** [comment]
@marcoherbst I have tested this feature with my personal email (muneeb2542@hotmail.com) first with a read only rights and then with full rights.Both times the account was created and the camera was shared successfully.

**Comment by marcoherbst** [comment]
@muneeb2542 perfect, thanks.
