### ISSUE TITLE
Remove Faraday Repo (to Gitlab)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#379]
@azharmalik3  ... I guess we're no longer using this: https://github.com/evercam/faraday-digestauth ?

If so, you could put it on Affan's list to move to Gitlab Private ?

Tks

**Comment by azharmalik3** [comment]
@marcoherbst It was used in old `evercam-api`. Now, we are not using anymore.

@affan00 move this to Gitlab Private.

**Comment by azharmalik3** [comment]
DONE.
