### ISSUE TITLE
Add logs for all create and update actions

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-media#386]
- [ ] Camera Create / Update
- [ ] Archive Create / Delete
- [ ] Cloud-recordings Create / Update / Delete

**Comment by marcoherbst** [comment]
There is also an open ticket (discussed with @ijunaidfarooq ) about maintaining user logs.

One possible path is to combine all of these logs into one place (adding user activities to camera activities).

I don't have strong opinions about this, though I could see some scalability issues wrt having them all in the same place. I had imagined we would probably, eventually, split these for ease of scaling. I've no good suggestions at present, but this need not hold back the first 3 from Azhar's list.

**Comment by marcoherbst** [comment]
Log IP address for all of these events.

**Comment by ijunaidfarooq** [comment]
I am moving user create / update log to https://github.com/evercam/evercam-media/issues/224. (its already been there with name of **Update Profile** `) and Also for now ignoring MD create/update log as we only have `get MD` endpoint right now!

**Comment by ijunaidfarooq** [comment]
This issue is completed.

for other's information: mostly we have client request IP in `X-Forwared-For` but according to devOps its been configured for `X-Real-IP` and by doing 
```
Plug.Conn.get_req_header(conn, "x-real-ip")
```
we can get client's IP but in case there is no IP we are getting remoteIP as 
```
conn.remote_ip |> Tuple.to_list |> Enum.join(".")
```

**Comment by marcoherbst** [comment]
Thanks for the explanation @ijunaidfarooq
