### ISSUE TITLE
Add nginx and Phoenix logs to AWS Cloudwatch

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#39]
@mosic I'm not sure that this is still your plan, but I wanted to cleanup Trello, so moving this on. Deal with it as you wish.

**Comment by mosic** [comment]
@marcoherbst That's still the plan, but it's more relevant to `evercam-devops` as it's set up on the server level. I've made an issue there a week ago: https://github.com/evercam/evercam-devops/issues/18

Closing this.
