### ISSUE TITLE
broken image in email on clip creation.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#396]
this might because this camera is a session auth camera (not basic auth) and it also happens with the sharing email.

![screenshot from 2016-05-11 14-19-26](https://cloud.githubusercontent.com/assets/6482077/15176262/aef1c9e0-1783-11e6-8be6-256345bce8ef.png)

**Comment by ijunaidfarooq** [comment]
done and deployed as well.

**Comment by ijunaidfarooq** [comment]
tested as well.. its working fine now!
