### ISSUE TITLE
Update timezone related code

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#398]
We're getting a lots of deprecation warnings related to the `timezone` gem:

>[DEPRECATED] `Zone#zone` will not be available in the next release of the `timezone` gem. Use `Zone#name` instead.
[DEPRECATED] Creating Zone objects using an options hash will be deprecated in the next release of the `timezone` gem. Use `Timezone::[]`, `Timezone::fetch` or `Timezone::lookup` instead.

**Comment by ijunaidfarooq** [comment]
@marcoherbst We don't have any such warnings now. Because we are not using timezone gem... we are using Calendar for such tasks now.. and there are no warnings as well related to that. so am closing this!
