### ISSUE TITLE
Add support for digest access authentication 

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#4]
Some cameras in Evercam system use https://en.wikipedia.org/wiki/Digest_access_authentication

Currently we support it by shelling out to curl ([snapshot_fetch.ex#L14](https://github.com/evercam/evercam-media/blob/908b64a1e02537a1e8c469099f5622e4f71273bc/lib/snapshots/snapshot_fetch.ex#L14)), which is not great.

Ideally, this would be implemented in [httpotion](https://github.com/myfreeweb/httpotion), which we use for requesting snapshots from the cameras, but if necessary we could probably switch to [httpoison](https://github.com/edgurgel/httpoison) with a small bit of work.

**Comment by marcoherbst** [comment]
In particular, Samsung Cameras use Digest Auth.

If you can't find an example online, ask and I'll try to get you one.

M

On 23 June 2015 at 14:36, Miloš Mošić <notifications@github.com> wrote:

> Some cameras in Evercam system use
> https://en.wikipedia.org/wiki/Digest_access_authentication
>
> Currently we support it by shelling out to curl (snapshot_fetch.ex#L14
> <https://github.com/evercam/evercam-media/blob/908b64a1e02537a1e8c469099f5622e4f71273bc/lib/snapshots/snapshot_fetch.ex#L14>),
> which is not great.
>
> Ideally, this would be implemented in httpotion
> <https://github.com/myfreeweb/httpotion>, which we use for requesting
> snapshots from the cameras, but if necessary we could probably switch to
> httpoison <https://github.com/edgurgel/httpoison> with a small bit of
> work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/4>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by shankardevy** [comment]
@mosic does the caller of `fetch` already have the knowledge of whether the camera supports plain, or digest or token authentication? or does it have to be identified dynamically trying one after the other?

Supposing the caller knows what type of authentication a camera supports and can pass on the appropriate arguments, can this be implemented as three different patterns on the same function named `fetch` something like https://gist.github.com/shankardevy/33ef2435bfe5c58bbdc8

**Comment by marcoherbst** [comment]
Good point.

Yes, we know the auth type. We get it from the Camera Model:

e.g.

https://api.evercam.io/v1/models/m1011

Does that answer the Q ?

M



On 23 June 2015 at 17:33, Shankar Dhanasekaran <notifications@github.com>
wrote:

> @mosic <https://github.com/mosic> does the caller of fetch already have
> the knowledge of whether the camera supports plain, or digest or token
> authentication? or does it have to be identified dynamically trying one
> after the other?
>
> Supposing the caller knows what type of authentication a camera supports
> and can pass on the appropriate arguments, can this be implemented as three
> different patterns on the same function named fetch something like
> https://gist.github.com/shankardevy/33ef2435bfe5c58bbdc8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/4#issuecomment-114564991>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by shankardevy** [comment]
yes, it does answer the question.

Basically then, the solution would be to refactor this https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L28-L52  or https://github.com/evercam/evercam-media/blob/master/lib/snapshots/snapshot_fetch.ex#L146-L155 so that `fetch` gets called with the appropriate arguments and create functions like https://gist.github.com/shankardevy/33ef2435bfe5c58bbdc8 to handle the different authentications.

**Comment by mosic** [comment]
@shankardevy The code is mostly messy and needs refactoring eventually, but that's not the real problem here. By shelling out to curl we lose on supervision, possible exceptions etc. so the actual solution is to add digest auth support to the library we use for http requests ([httpotion](https://github.com/myfreeweb/httpotion)).

**Comment by ephe-meral** [comment]
how about something along the lines of this draft... https://gist.github.com/ephe-meral/fbb39af2f5e55b564716

**Comment by shankardevy** [comment]
@mosic I created a discussion here https://github.com/myfreeweb/httpotion/issues/60 assuming this is what you want. I haven't started working on the implementation as mention in the httpotion issue but will start working on it soon. Hope this  is the direction you want to take this forward.

**Comment by mosic** [comment]
@ephe-meral Yes, something like that would be okay if we wanted to keep the implementation on our side. I'm getting a couple of errors but it looks good.

@shankardevy Excellent, that's what I was hoping for.

**Comment by shankardevy** [comment]
@mosic since HTTpotion doesn't implement any of the actual code as an http client, rather, works as a syntactic sugar on top of ibrowse, our need for getting digest auth may get pushed further down to ibrowse stack (which is on erlang) and not on HTTPotion.

I had my first stab at patching ibrowse today https://github.com/cmullaparthi/ibrowse/commit/d8b9331688820d8a05e995d002dc7a0cd1cee339 and I see it's near completion. Though not fully functional yet, this would be the direction to go, if we want to keep the implementation of Digest Auth outside EvercamMedia as per your comment (which I think is actually right).

Once ibrowse path is working and accepted, HTTPotion may need another PR to accept digest auth.

**Comment by shankardevy** [comment]
@mosic when an app makes a call to the url like /v1/cameras/:id/live/snapshot, it passes a token param and this token param is then passed on to the Snapshot fetcher. Can you point me to the right direction on where this token gets generated and sent to the app?

**Comment by mosic** [comment]
@shankardevy Sure, the token is generated on the Evercam API server (written in Ruby) and passed to the Elixir server in the redirect url. You can find the code here: [snapshot_routes.rb#L19-L56](https://github.com/evercam/evercam-api/blob/4af1c963228dc07668f86ad648ad401a26554cb2/app/api/v1/routes/snapshot_routes.rb#L19-L56)

**Comment by marcoherbst** [comment]
This appears to not be working anymore ...

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-media/commit/b126330d81693b8c6ecc3690976fa2d9320487ba.
