### ISSUE TITLE
If vendor / model is specificied, dont allow custom URLs

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#402]
Currently we can specify a vendor / model and then change the snapshot URL.

I think that's a bad idea.

Let's make it so that if vendor / Model is specified, then the URL is also fixed.

This implies a few things, incl:
- [x] Any camera where the model has a custom URL needs to be set to other-default
- [x] Lock the URLs so they cant be changed , API & Dash & Apps.
- [x] Work out what's going on with all the other-defaults and make the changes necessary to get rid of them.

@azharmalik3  , I think you might be the only fellow who can handle this. @fteem it's probably good that you are aware of such a change, it's not small.

**Comment by azharmalik3** [comment]
Done.
