### ISSUE TITLE
Shared Email reminders

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#403]
- [x] When a share request is 7 days old and not accepted, send a reminder to the sharee. cc The Sharer. Repeat this every 7 days.
- [x] The Sharee should also be able to say "Stop sending me these reminders" (equivalent to revoking the request).
- [x]  If they to revoke the request, the sharer gets an email " XX has revoked the request to share camera XX with them."  In this case, bcc vq and mh. (Temporary measure while we work out how this is used).
- [x] When a pending share is accepted (the sharee creates an account) then send an email to the sharer to say "xxx has accepted your share request. ..."

**Comment by marcoherbst** [comment]
To stop receiving these reminders, please <A>click here<A>. If you have any questions, please contact Vinnie Quinn on +353879871869

**Comment by azharmalik3** [comment]
@marcoherbst after 3 reminders cancel share-request? or just stop reminders after 3?

**Comment by marcoherbst** [comment]
I think just stop sending them, do not revoke the request.

**Comment by azharmalik3** [comment]
Done.
