### ISSUE TITLE
Improved Logs .... Interface & What we log ....

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#404]
I thought the screenshot from New Relic seemed like a nice way to filter between different types of events:

![screenshot-rpm newrelic com 2015-10-14 08-39-50](https://cloud.githubusercontent.com/assets/5648894/10477599/564fc4f6-724f-11e5-832a-bf92d4903542.png)

**Comment by marcoherbst** [comment]
Have alook @ Mailgun, it shows the events with the option to expand and see the full request. Very nicely done.

**Comment by marcoherbst** [comment]
Closing this. It's more dash related.
