### ISSUE TITLE
During sign up process media accepts capital letters for email field

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#418]

**Comment by marcoherbst** [comment]
My preference for this would be to accept CAPITALS but auto-fix them to non-capitals.

Means max chance of user getting what they want without slowing them down. right?

**Comment by Zulqarnain-Mustafa** [comment]
Yes this is what we will do.

**Comment by ijunaidfarooq** [comment]
Fixed here.. https://github.com/evercam/evercam-media/pull/443 FYI @Zulqarnain-Mustafa
