### ISSUE TITLE
Double camera entries in dash

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#452]
![screen shot 2016-09-08 at 12 13 06 pm](https://cloud.githubusercontent.com/assets/8174314/18340517/f7c02948-75be-11e6-846c-857fef1a67da.png)

In Admin only shows single time but in dash it shows 2 times.

**Comment by ijunaidfarooq** [comment]
can you specify the user account? e.g username or email? of the effected user..

**Comment by ijunaidfarooq** [comment]
fixed.
