### ISSUE TITLE
Timeout on remembrance cam shares

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#463]
My guess is that this is due to me requesting https://dash.evercam.io/v1/cameras/evercam-remembrance-camera from the account owner (evercam) 

this would have triggered a request for shares which would be huge and has timed out.

Ideas:
1. pagination (first 100 only ?)
2. different way of loading data (ajax type thing?)
3 ... don't know.

I guess it's only an issue for this camera which has lots of shares. We could also treat these as a different type of share.

Ideas?

**Comment by marcoherbst** [comment]
One way  of solving this is to hard-code, for this camera, don't load shares. (we did that before, I think).

**Comment by ijunaidfarooq** [comment]
we can check for all those cameras who have more than 50 or 75 shares then we can paginate those shares.. instead of doing hard code.

**Comment by marcoherbst** [comment]
Hardcode a server side solution to return empty data for this camera. Temp fix, but it's ok.

**Comment by ijunaidfarooq** [comment]
I have done it and added a test for it as well to ensure the results. everything is fine.
