### ISSUE TITLE
Careful logging of failed attempts at adding a camera / snapshot testing

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#468]
This is probably the most significant hurdle for most users.
We should carefully gather this data to see what are the patterns of failure and where we should focus our energies to help.
It might even warrant it's own DB table.

**Comment by azharmalik3** [comment]
Now, we are logging all failure errors of `add-camera` and `new-user`.

like: 
```request_id=te3shn47vuo7lpv15f5dlm19f90ivobm [error] [camera-create] [%{name: ["Camera Name is too long. Maximum 24 characters."]}]```
