### ISSUE TITLE
Camera status not updating (weighbridge-b)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#48]
This camera, was offine:
https://dash.evercam.io/v1/cameras/weighbridge-b  (meherbst , mehcam)

I fixed the camera, went to edit details, tested snapshot  (success) saved and it did not come back online on Evercam.

Edited again.
changed Vendor / Modrl
Edited again.

Tried "refresh" from /live-view

.... still not online.

changed recording settings ...

.... still not online.

@mosic we looked at this.

**Comment by mosic** [comment]
This will be handled by https://github.com/evercam/evercam-media/issues/20, closing.
