### ISSUE TITLE
First name and last name regex is not working

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-media#488]
Our first name , last name regex is passing spaces as a name. 

` @name_regex ~r/^[\p{Xwd}\s,.']+$/`

```
iex(2)> Regex.match?(~r/^[\p{Xwd}\s,.']+$/, "   ")
true
iex(3)> 
```

**Comment by marcoherbst** [comment]
@ijunaidfarooq  , more info please. What is your suggestion? 

It's starting to seem a little bit silly how much effort we have put into Regex over the last 5 years. It would be nice if you would explain a better plan.

**Comment by ijunaidfarooq** [comment]
My suggestion was to implement that [regex](http://stackoverflow.com/a/2385967/4952770).. But then Milos suggested the above one. 

as we are keeping the same regex on evercam-models and media

I just tested the model's regex and Its passing `"   "` as a valid name as well.

**Comment by ijunaidfarooq** [comment]
```
=> #<User:0x00000003b25090> {
          :billing_id => nil,
        :confirmed_at => nil,
          :country_id => 97,
          :created_at => 2016-09-30 06:54:07 +0000,
           :firstname => "Denis",
                  :id => 68058,
          :insight_id => nil,
            :is_admin => false,
       :last_login_at => nil,
            :lastname => "Anthony",
      :payment_method => 0,
         :reset_token => nil,
  :stripe_customer_id => nil,
    :token_expires_at => nil,
          :updated_at => 2016-09-30 07:50:42 +0000,
            :username => "lui-même",
          :vat_number => nil
}
[3] evercam_dashboard »  @user.firstname = "  "
=> "  "
[4] evercam_dashboard »  @user.save
=> #<User:0x00000003b25090> {
          :billing_id => nil,
        :confirmed_at => nil,
          :country_id => 97,
          :created_at => 2016-09-30 06:54:07 +0000,
           :firstname => "  ",
                  :id => 68058,
          :insight_id => nil,
            :is_admin => false,
       :last_login_at => nil,
            :lastname => "Anthony",
      :payment_method => 0,
         :reset_token => nil,
  :stripe_customer_id => nil,
    :token_expires_at => nil,
          :updated_at => 2016-10-04 15:08:13 +0500,
            :username => "lui-même",
          :vat_number => nil
}
[5] evercam_dashboard »  

```

**Comment by ijunaidfarooq** [comment]
my suggestion is to do:

as the first option trim the name for spaces at first place and then check the length in ecto changeset

`validate_length(changeset, :firstname, min: 3, max: 100)`


OR

`/^[a-z ,.'-]+$/i`
for such names as:

Mathias d'Arras
Martin Luther King, Jr.
Hector Sausage-Hausen

OR Support international names with super sweet unicode:

```
/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$/u
```

I mostly go with the first idea..

**Comment by ijunaidfarooq** [comment]
I did this with the first option.

While using trim the spaces will be removed. In case if the user has added only spaces it will be caught and error will be returned. 

@Zulqarnain-Mustafa FYI it's been done.
