### ISSUE TITLE
Camera Offline periodic reminders

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#498]
@marcoherbst will discuss with @vinnieq

**Comment by marcoherbst** [comment]
[  ]  24 Hrs after last_online_at
[  ]  7 Days after last_online_at

.... also, if "is_online=true" , then why have "last_online_at" value at all ?  .... should this not be (if it is needed at all for an online camera) ... "Went_offline_at" ?

@azharmalik3

**Comment by azharmalik3** [comment]
@marcoherbst ah, we don't need the new field. `last_online_at` will solve our problem.

**Comment by azharmalik3** [comment]
Done. I got a reminder after 24 hours.
