### ISSUE TITLE
Add support for cookie based authentication

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#5]
See also: https://github.com/evercam/evercam-media/issues/4

***

Some cameras (notably, Ubiquiti cameras) require cookie based authentication. This is an example of working authentication code written in C#: https://gist.github.com/mosic/c028b8973b5a890145fe

Above class is used to get the cookie by passing three arguments - camera url, username and password:

``` c#
UbiquityAuthentication ub =
    new UbiquityAuthentication("http://example.com:80", "username", "password");
string cookie = ub.GetAuthenticationCookie();
``` 

That cookie should then be used for a "Cookie" header and used for future snapshot requests.

***

Like I mentioned in https://github.com/evercam/evercam-media/issues/4, this too would be ideally implemented in [httpotion](https://github.com/myfreeweb/httpotion) or [httpoison](https://github.com/edgurgel/httpoison).

**Comment by shankardevy** [comment]
@mosic how long does this cookie live? Is there a need for caching this cookie per camera or is the cookie gets generated for each request?

/cc @marcoherbst

**Comment by marcoherbst** [comment]
This is more a Q for @azharmalik3 , he has more experience of this in
reality.

m

On 23 June 2015 at 17:36, Shankar Dhanasekaran <notifications@github.com>
wrote:

> @mosic <https://github.com/mosic> how long does this cookie live? Is
> there a need for caching this cookie per camera or is the cookie gets
> generated for each request?
>
> /cc @marcoherbst <https://github.com/marcoherbst>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/5#issuecomment-114565649>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
@shankardevy the cookie will expire at the end of session.

**Comment by marcoherbst** [comment]
@mosic ... 

1. I see that https://api.evercam.io/v1/models/aircam-dome reports basic auth, it should be cookie auth. Any reason that's hard to fix? (and all other cams from that vendor).

2. Your current Fetch controller seems to ignore this info anyway. Is it correct we would want to change that?
https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L66

3. This PATCH endpoint doesn't seem to include auth-type as a parameter. Comments?
https://dash.evercam.io/swagger#!/models/PATCH_models_id_format

4. That PATCH uses "default-password" (seems sensible) ... the JSON response just says "password" (seems inconsistent and misleading). Any comment on that?

**Comment by mosic** [comment]
@marcoherbst The `evercam-api` was built with the assumption of using only basic auth but can be extended with a bit of effort. We need to do two things: add support for specifying the auth type and modify the current data to specify correct auth for  all models.

In the meantime, on `evercam-media` we can keep using basic auth as default and trying digest on auth error as we're doing now.

**Comment by marcoherbst** [comment]
@shankardevy ok, we'll implement this using the fallback method and create a separate issue to replace that code with model based auth type evercam/evercam-api#362

**Comment by shankardevy** [comment]
with the PR https://github.com/evercam/evercam-media/pull/12

the following should login to the remote url, fetch the cookie, and use the cookie to retrieve the snapshot.
```
  EvercamMedia.HTTPClient.get(:cookie_auth, "http://ip.ad.dre.ss:8013/snapshot.cgi", "put_username", "put_password")
```
