### ISSUE TITLE
HLS stream not working

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#510]
Using Apple "HTTP Live Streaming Tool" here are error details which we are getting:

Zulqarnains-MBP:~ `zulqarnainmustafa$ mediastreamvalidator HLS URL`
mediastreamvalidator: Version 1.2(160525)

[/live/==/index.m3u8] Started root playlist download
Have root playlist response error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f9c8640d420 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://media.evercam.io:4000/live/==/index.m3u8?camera_id=, NSErrorFailingURLKey=http://media.evercam.io:4000/live/==/index.m3u8?camera_id=, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

**Error: Illegal MIME type
--> Detail:  MIME type: (null)**
--> Source:  http://media.evercam.io:4000/live/==/index.m3u8?camera_id=

**Error: The request timed out.
--> Detail:  (null)**
--> Source:  http://media.evercam.io:4000/live/==/index.m3u8?camera_id=

HLS stream also does not play with VLC Player as well.

**Comment by azharmalik3** [comment]
Actually, the system failed to resolve HLS URL due to HTTP port in the link. Now removed port from URL and also used https URL for HLS.
