### ISSUE TITLE
Identify the response as jpeg nor not using magic numbers

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#52]
@mosic first, do we need to check if the response is jpeg or not? What else could be the response when we get a reply with status code 200?

Then, if we need really to need check if this, then I suggest that we use Jpeg [Magic numbers](
https://en.wikipedia.org/wiki/Magic_number_%28programming%29) instead of this
https://github.com/evercam/evercam-media/blob/master/lib/snapshots/snapshot_fetch.ex#L53-L57

where a byte sequence which is not a string is taken as jpeg.

**Comment by mosic** [comment]
@shankardevy Depends on a camera manufacturer/model, it could be text or an XML response saying  "The Device is Busy" or similar. You can't trust neither the response status nor headers.

I haven't seen one false positive with the simple check I made though but using magic numbers for detecting jpegs seems like a good idea.

**Comment by shankardevy** [comment]
this is complete as part of the [refactor](https://github.com/evercam/evercam-media/pull/70)  merge
