### ISSUE TITLE
Does camera worker start when adding a new camera?

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#54]

**Comment by shankardevy** [comment]
@mosic I don't see any code in media that start the worker for new camera. Do you have any idea on how to approach it? is it planned?

**Comment by mosic** [comment]
@shankardevy I mentioned two possible approaches on the issue about updating existing camera workers: https://github.com/evercam/evercam-media/issues/20

Basically, listen to changes on the `cameras` table or get a notification from the `evercam-api` using `sidekiq` for example. Those are just two options, I'm open for better ones.

**Comment by shankardevy** [comment]
@mosic listening on table change, I think, is going to be too much of a burden because the `camera` table gets updated too often. While changes due to new camera might be not so high, changes due to camera status update or thumbnail urls are too often. So restarting a camera worker when a camera detail changes could be lot trickier. Also we need to put in extra checks to avoid cyclic infinite loops where we listen to camera table change which trigger changes in the camera table again....

How about we have a secret token on `media` and share it only with `evercam-api`. When a new camera is added or an existing camera is modified, it sends  non-blocking call to a new endpoint on `media` with the secret token mentioning if a camera got added or modified. We then either create a worker or restart the worker whichever the case maybe.

**Comment by shankardevy** [comment]
@vinnieq  @marcoherbst regarding your email about new camera not recording, it's still a work to be done with integration happening between media and api. This issue tracks it. The recent changes to the snapshot workers refactor could make it easier but still need our api to inform the media server whenever a camera information is updated. Maybe we could have a quick call @marcoherbst @mosic  to discuss this?

**Comment by shankardevy** [comment]
This will be handled by #20, closing.
