### ISSUE TITLE
Sign up api call does not return complete message if username is invalid

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#543]
<img width="689" alt="screen shot 2016-11-11 at 3 48 54 pm" src="https://cloud.githubusercontent.com/assets/8174314/20212722/85979190-a826-11e6-8046-8200f2fb727c.png">

The message should be like following screen shot. It should be complete and user friendly.

<img width="861" alt="screen shot 2016-11-11 at 3 46 39 pm" src="https://cloud.githubusercontent.com/assets/8174314/20212723/8612489a-a826-11e6-8363-588019714db5.png">

**Comment by ijunaid8088** [comment]
done

**Comment by Zulqarnain-Mustafa** [comment]
@ijunaid8088  when you do fix like that please show the new response message as well. Thanks
