### ISSUE TITLE
Remove dependency on eredis

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#59]
Currently we are use redis as a workaround because invalidating memcache was not working for some strange reasons when initially tried by Milos. We could avoid using redis on Media if we could successfully  purge  memcached data of a camera directly from Media.

**Comment by mosic** [comment]
For clarification, the "strange reason" is that the Ruby library we use on `evercam-api`, [dalli](https://github.com/mperham/dalli), does not use a same hashing mode for the key as the Erlang library [mcd](https://github.com/EchoTeam/mcd) that I tried it with.

**Comment by mosic** [comment]
There doesn't seem to be a strong reason to do this, closing.
