### ISSUE TITLE
Remove unwanted S3 libraries 

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#60]
Due to various trial and errors, we have now two different libraries erlcloud, minis3 used in different places. If possible remove all of them since we don't do much with the library or else use only one.

**Comment by mosic** [comment]
Mostly fixed in https://github.com/evercam/evercam-media/pull/87. As mentioned there, this will be complete after we implement new `thumbnail_url` functionality.

**Comment by marcoherbst** [comment]
Is this done? @mosic

**Comment by mosic** [comment]
Yep, I did it recently: https://github.com/evercam/evercam-media/commit/870fd9822293ec6a85f88a13ff4184b917c57e09 and https://github.com/evercam/evercam-media/commit/d72c34de6f0574efe2014bf434dc04ef296ab50d.
