### ISSUE TITLE
Do not store snapshot in s3 from live view

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#62]
It's just remove remove this one line https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L99
and slightly modifying the response to complete this.

I am in favor of removing this as this causes unnecessary process crashes due to unique_id violation in postgres when worker and live view constantly keep updating snapshots for the same timestamp.

This now depends on reply from @mh

**Comment by marcoherbst** [comment]
Ok, do it.

M

On 15 September 2015 at 14:05, Shankar Dhanasekaran <
notifications@github.com> wrote:

> It's just remove remove this one line
> https://github.com/evercam/evercam-media/blob/master/web/controllers/snapshot_controller.ex#L99
> and slightly modifying the response to complete this.
>
> I am in favor of removing this as this causes unnecessary process crashes
> due to unique_id violation in postgres when worker and live view constantly
> keep updating snapshots for the same timestamp.
>
> This now depends on reply from @mh <https://github.com/mh>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/62>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
