### ISSUE TITLE
More elegant handling of an XML response such as the one below ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#63]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ResponseStatus xmlns="urn:psialliance-org" version="1.0">
<requestURL>/ISAPI/Streaming/channels/201/picture</requestURL>
<statusCode>3</statusCode>
<statusString>Device Error</statusString>
<subStatusCode>deviceError</subStatusCode>
</ResponseStatus>

(From our ardmac cams ... not sure why , but this resulted in broken IMGs .....)

Possibly this ticket can be merged into another existing one.

**Comment by shankardevy** [comment]
@marcoherbst I need more information on this error. Maybe we could have a quick call to discuss details.

**Comment by marcoherbst** [comment]
Sure. The text in the initial description is what the camera was returning, along with a 200 OK. I got the impression that this was causing trouble for the dashboard. .... NB.... we can live with this to some extent, I'm not convinced that we should be checking the integrity of every single response, this is an FYI as much as anything.

**Comment by marcoherbst** [comment]
Closing this, seems it is not causing a problem at the moment.
