### ISSUE TITLE
Configuration variables set in config.exs aren't available using Application.get_env in the compiled application

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#69]
For example onvif is set in `config.exs`:

```
config :onvif,
  default_profile: "Profile_1"
```

But returns `nil` when requested with `Application.get_env(:onvif, :default_profile)`.

**Comment by jgarciasacristan** [comment]
Actually, having a generic default configuration does not add any value really. The idea was to have a place to change it quickly if we needed to do it for my demo two weeks ago. At this moment, having  it hard coded to "Profile_1" in the controller's code is as good or bad as the default profile. In my opinion, the proper fix is to have the profile defined as a property in the camera database.

**Comment by mosic** [comment]
@jgarciasacristan Yes, we agreed on https://github.com/evercam/evercam-media/pull/67. We will need variables from `config.exs` for other things though, so I'd consider this a bug.

**Comment by jgarciasacristan** [comment]
Sorry for the duplication. You are absolutely right. :-)

**Comment by marcoherbst** [comment]
@mosic who should this be assigned to?

**Comment by mosic** [comment]
@marcoherbst This turned out to be correct behavior for the app config. To make it work like I expected in this specific example, the config should have been:

``` elixir
config :evercam_media, :onvif,
  default_profile: "Profile_1"
```

And then fetched like this:
``` elixir
Application.get_env(:evercam_media, :onvif, :default_profile)
```

Btw in new versions of Elixir using code from the issue description raises a warning.
