### ISSUE TITLE
Identify the source of problem where the media server randomly goes idle

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#72]
In a span 24hrs, there is a repeated pattern of media server going idle (as understood by New Relic stats) for an hour.

**Comment by shankardevy** [comment]
I happened to check media server yesterday randomly and it was almost idle for several hours and was slowly picking up. What was meant as a quick check, ended up a few hours of debugging and this is my understanding. There are multiple bugs, at least more than two, that are causing this issue. I tried to find out two of them now:

1. to_date variable used for testing if a camera is scheduled for recording return time 22.59 for all cameras recording per second. So this leaves a window of 1 hr 1 min where the schedule will return false and all these camera workers will be idle for exactly the same period of time.

2. I found a camera schedule where Sunday's schedule is stored in db as NaN which crashes the poller process cascading to the worker process and both of them get restarted continously until it's Monday.

The above are the two issues that I found out.

3. When checking the number of active registered processes during the idle time, I saw a great fluctuation happening from between 150 - 2000 about every second. This means that workers are constantly crashing for some reason and restarting during the idle time. So there is some bug that is triggered during a certain time range that crashes most of the workers but after that time passes on, workers start behaving normally. This I call it, "Devil's Time" happening mostly at mid night for strange reasons yet unknown.

**Comment by mosic** [comment]
Nice analysis @shankardevy. That `NaN` bug was particularly interestin, so I looked into it. It turns out that it happened with only one time period on one camera - a leftover from testing the initial cloud recording settings. That shouldn't happen any more, but we should be able to handle that kind of input in `evercam-media` regardless.

**Comment by mosic** [comment]
This seems like it was accidentally closed by mentioning "Fixes partly" in https://github.com/evercam/evercam-media/pull/77. Reopening.

**Comment by shankardevy** [comment]
commits https://github.com/evercam/evercam-media/commit/e030dec60c32a30f83a4600bea5428e502d9f73c and https://github.com/evercam/evercam-media/commit/ad27d898c799be68d3aa21f944d7e343bb52ac93

should resolve any error with scheduler

**Comment by shankardevy** [comment]
there was another with the scheduler due to timezone differences which is fixed by https://github.com/evercam/evercam-media/pull/84

**Comment by marcoherbst** [comment]
Haven't seen this problem for ages. closing. @mosic hope that's ok.
