### ISSUE TITLE
Improve the database event handler for snapshot worker

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#74]
[db event handler](https://github.com/evercam/evercam-media/blob/master/lib/evercam_media/snapshot/db_handler.ex) needs clean up of unwanted db updates and code.

**Comment by shankardevy** [comment]
Just realized that the next cleanup is due after we resolve [thumbnail generation](https://github.com/evercam/evercam-media/issues/46). @milos and I already discussed this and we both agree on the steps outlined as my suggestion in the linked issue.

**Comment by marcoherbst** [comment]
Suspect this is now dealt with. @azharmalik3 , if you think this is no longer relevant, please close.

**Comment by azharmalik3** [comment]
This is already completed.
