### ISSUE TITLE
Handle emfile errors

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-media#81]
The logs shows a lot of `%HTTPotion.HTTPError{message: "emfile"}` which occur when we have [too many open files](http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me)

However `ulimit -a` on server return 

`open files                      (-n) 1000000`

I don't think we have so many files open. So HTTPotion reporting 'emfile' is bit strange.

1. Find out what this error means and why this occurs
2. Fix it.

**Comment by shankardevy** [comment]
@mosic do you know of any reason why this occurs or a solution to fix the same?

**Comment by mosic** [comment]
@shankardevy I actually looked into this briefly before and modified the `ulimit`, the default is 4000. I haven't come to a conclusion though.

**Comment by mosic** [comment]
This was solved soon in October.
