### ISSUE TITLE
Camera Online / Offline notifications

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#88]
This is a placeholder for a chat with @mosic 

- [x] Have a reasonable way to determine whether a camera is offline
- [x] When a camera is offline begin a sequence of events to bring it back online
- [x] After 60 seconds of trying to get the camera back online, send an email to the customer, with the most recent jpeg.
- [ ] After 1 hr, send a reminder.
- [ ] After 1 day send a reminder.
- [x] Notifications should be enabled / disabled on a per camera basis 
- [ ] Ability to manually turn a camera offline (this means not sending offline recovery emails)
- [ ] Little notifications showing on the dashboard ...
- [ ] Consider how this will translate to push alerts.

**Comment by marcoherbst** [comment]
![screenshot 2015-10-12 16 50 04](https://cloud.githubusercontent.com/assets/5648894/10432214/a9203a98-7101-11e5-8584-4b1afaeac5ed.png)



![screenshot 2015-10-12 16 49 59](https://cloud.githubusercontent.com/assets/5648894/10432213/a91ca5a4-7101-11e5-907e-e07feb723389.png)


For online/offline notifications, we can think of having multiple emails & push notifications.

**Comment by marcoherbst** [comment]
Useful definition from EagleEye:

Alerts/Notifications 
Alerts or Notifications are generated from Events when the User has created criteria to create them. Alerts may be given in any number of methods (on screen, email, text message, etc..). Alerts may have to be acknowledged by the User. The EEVBS will collapse alerts into a single alert to avoid creating too many that would be annoying. Alerts are almost always generated from Events. Alerts are commonly generated when Cameras are turned off, go offline, or when motion is detected in areas where there should not be any motion. The Alert may or may not include the video or other Assets of interest. Alerts sent to Users automatically create a Save to provide organized access to the related image, video, and meta-data. The URL to the save is provide within the Alert for immediate access. (THIS IS PROBABLY ACTUALLY A SHARE, A GROUP OF SAVES, SINCE ALERTS USUALLY “CLUSTER”)


Our approach is obviously somewhat different.

**Comment by marcoherbst** [comment]
https://dash.evercam.io/swagger#!/cameras/GET_cameras_id_format
How about:

      "is_online": true,
      "is_online_email_owner_notification": true,

@mosic ... better suggestion?

M

**Comment by mosic** [comment]
@marcoherbst That may be good enough as a starting point.

**Comment by marcoherbst** [comment]
Re: Item " When a camera is offline begin a sequence of events to bring it back online"

Would a workable solution be: Every 60 seconds attempt a POST snapshot for all offline cameras. ?  (which, if successful would bring the camera back online).

If so, then that sounds like the sort of thing that could become an issue on its own and could be completed in the near-term?

**Comment by marcoherbst** [comment]
This issue seems too big & unrealistic. I'm going to make one that is more achievable and put this task further into the future. 

https://github.com/evercam/evercam-media/issues/209

**Comment by marcoherbst** [comment]
@mosic  @azharmalik3  @ijunaidfarooq  

I think this is no longer a top priority task in that it can be worked on after Milos is gone. I'm moving it into the future. Any complaints?

**Comment by marcoherbst** [comment]
Task is mostly done and a bit too vague. Will create a new issue for offline reminders.
