### ISSUE TITLE
Snapshots are being saved to the database and not uploaded to S3 (maybe)

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#95]
@shankardevy The server seems to be saving snapshot records in the database even if they're not uploaded to S3. You can see a lot of errors related to that if you open any camera and play recordings in the dashboard.

The other reason may be that the timestamps now differ, not sure if you changed something in that area.

This is where the error is coming from on the API: https://github.com/evercam/evercam-api/blob/master/app/api/v1/presenters/snapshot_presenter.rb#L31

Let me know if you need more information to debug this.

**Comment by shankardevy** [comment]
thanks @mosic for bringing this important issue into notice.
