### ISSUE TITLE
Repair script for lost snapshots 1st Oct - 15th October

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#97]
During this period an unknown number of snapshots were saved with the wrong timestamp.

We may need to write a script to recover them.

Unassigned. Let's wait and see if it's an issue.

@vinnieq just FYI

**Comment by eugenehp** [comment]
I think we can try to sequence rights records from the table by the different time format.

**Comment by marcoherbst** [comment]
I'm going to close this. @vinnieq tell me if you remember any reason to worry about it.

**Comment by vinnieq** [comment]
no, tiny chance of it ever coming up

v



Evercam.io <http://www.evercam.io/> - Cameras Unleashed
Mobile (Irl) : +353 87 987 1869
ie.linkedin.com/in/vinniequinn
@vinniequinn  / @evrcm
