### ISSUE TITLE
RTSP > RTMP timedelay increases over time.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#98]
We currently solve this by restarting the ffmpeg process every 60 mins ( ? @mosic ) 

There may be a "smarter" way of handling this.

@rajmohanb  , I thought you might be interested to know that we have this issue here too, as you've seen it in the gateway when transcoding h264 > vp8

M

**Comment by rajmohanb** [comment]
@marcoherbst - RTSP & RTMP are signaling protocols and conversion might not be costly in terms of CPU cycles. What about media itself? Does h264 received from RTSP server get converted to some other codec (like VP8) when sending over RTMP or it's used as it is? I am a noob as far as RTMP is concerned. I would be interested to know the ffmpeg command/parameters used in this case.

**Comment by marcoherbst** [comment]
Luckily, it's an open source project:

https://github.com/evercam/evercam-media/search?utf8=%E2%9C%93&q=ffmpeg

:)

I thought we were doing HLS somewhere but I see no mention of it together
with ffmpeg @mosic  ?

https://github.com/evercam/evercam-media/search?utf8=%E2%9C%93&q=HLS&type=Code

M

On 16 October 2015 at 16:51, rajmohanb <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> - RTSP & RTMP are signaling
> protocols and conversion might not be costly in terms of CPU cycles. What
> about media itself? Does h264 received from RTSP server get converted to
> some other codec (like VP8) when sending over RTMP or it's used as it is? I
> am a noob as far as RTMP is concerned. I would be interested to know the
> ffmpeg command/parameters used in this case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/98#issuecomment-148752627>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@marcoherbst Nginx-RTMP generates HLS automatically when it takes RTSP and creates RTMP stream, that's why it's not mentioned in that piece of code.

**Comment by marcoherbst** [comment]
I haven't noticed this in ages, I'm just going to close it.
